extends:
  - airbnb-base
  - prettier
plugins:
  - jest
env:
  jest: true
rules:
  no-console: 'off'
  no-constant-condition:
    - error
    - checkLoops: false
  no-param-reassign:
    - error
    - props: false
