version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm ci
  build:
    commands:
      - npm run deploy
  post_build:
    commands:
      - touch dummy.zip

artifacts:
  files:
    - dummy.zip
