# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: tgbot

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ${env:AWS_REGION, 'ap-northeast-1'}
  memorySize: 512
  timeout: 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/*"
  deploymentBucket:
    blockPublicAccess: true
  tracing:
    lambda: true
  logRetentionInDays: 14

plugins:
  - serverless-plugin-include-dependencies
  - serverless-pseudo-parameters

package:
  individually: true
  exclude:
    - ./**

# The `functions` block defines what code to deploy
functions:
  coopReminder:
    handler: app/coopReminder.handler
    description: Telegramお知らせbot
    # The `events` block defines how to trigger the handler code
    events:
      - schedule:
          name: weekly-event
          description: '毎週定期的に起動するイベント'
          rate: cron(0 11 ? * TUE *)
          enabled: true
          input:
            chat_id: -25511902
            text: '締切時刻が近づいています。\n注文はお早めに。'
